name: Rodrigo Davies
markdown: redcarpet
pygments: true
baseurl: /blog
url: http://www.rodrigodavies.com/blog
description: A blog about how technology and media impact communities and governments, and the ways they are adapting to new challenges and opportunities.
keywords: crowdfunding, communities, media, civic, civic crowdfunding, mit, rodrigo, davies, rodrigodavies